### ISSUE TITLE
JSON output ADC naming error?

### ISSUE THREAD

**Issue by jbuck2005** [Burtond/Electrodacus#2]
Line 217:			"ADC2": ADC2,
Line 218:			"ADC**2**": ADC3,
Line 219:			"ADC**2**": ADC4,

Should they perhaps read:
Line 217:			"ADC2": ADC2,
Line 218:			"ADC3": ADC3,
Line 219:			"ADC4": ADC4,

**Comment by Burtond** [comment]
Naming updated, thank you

**Comment by jbuck2005** [comment]
Still wrong in current version
