### ISSUE TITLE
Code fix: External_load only storing integer value

### ISSUE THREAD

**Issue by jbuck2005** [Burtond/Electrodacus#3]
> 149:      External_load = float(External_load / 1000)
> 150:	External_load = round(External_load, 3)

Swapping lines to read:
> 149:	External_load = round(External_load, 3)
> 150:      External_load = float(External_load / 1000)

Allows the script to store the current (in amps) to 3 decimal places. The original code truncates the current as an integer value.

**Comment by Burtond** [comment]
Using the round function first does nothing as the number from SBMS is an integer.  The rounding after the division rounds to three decimal places as it should.
