### ISSUE TITLE
Code modification: Add cell voltage monitoring

### ISSUE THREAD

**Issue by jbuck2005** [Burtond/Electrodacus#5]
I have a 4S battery, so my configuration has monitoring for cells 1,2,7,8. The modification below adds cell voltage monitoring to the InfluxDB data:

Add between:
> 219:			"ADC2": ADC4,
> .
> .
> .
> 220:			"Heat 1": heat1,
```
220:                      "Cell 1": Cell1,
221:                      "Cell 2": Cell2,
222:                      "Cell 7": Cell7,
223:                      "Cell 8": Cell8,
```

**Comment by Burtond** [comment]
Added Cell monitoring for all cells, thank you
