### ISSUE TITLE
Delta returns invalid value (4S system; computation seems to expect 8S)

### ISSUE THREAD

**Issue by jbuck2005** [Burtond/Electrodacus#7]
The value for delta seems to return an invalid value if the calculation uses all cells when less than 8 are actually being used.

Eg. In a 4S configuration, only cells 1,2,7,8 are used but the current delta computation uses cells 1...8

If I remove cells 3,4,5,6 from the computation, the correct delta value is being passed.
Perhaps this can be remedied by only considering non-zero values in the differential computation.

**Comment by Burtond** [comment]
I just posted an update that will ignore zero values.  I hope this corrects the issue.

**Comment by jbuck2005** [comment]
I like your work btw ... I don't mean to pester you with the changes; I merely want to help your script succeed.
You have probably guessed that I am no coder myself, so some of the things I have submitted were from brute-forcing and "just seeing what it would do".
Thanks for your work on this by the way!

James

________________________________

**Comment by Burtond** [comment]
I'm glad to share whatever I can and I really appreciate the constructive feedback.  It's about time that I try and share some of what I've been working on to help others...I take so much from the web and other work, I've been needing to give back for a long time now :)
